name: time-travel

on: 
  push:
  pull_request:
    branches: 
      - staging

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.x'
          architecture: 'x64'
      - run: python -c "import sys; print(sys.version)"
